# Generated by Django 6.0 on 2026-01-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Proje Adı')),
                ('aciklama', models.TextField(verbose_name='Proje Açıklaması')),
                ('resim', models.ImageField(upload_to='proje_resimleri/', verbose_name='Proje Görseli')),
                ('github_link', models.URLField(blank=True, verbose_name='GitHub Linki')),
                ('demo_link', models.URLField(blank=True, verbose_name='Canlı Önizleme Linki')),
                ('teknolojiler', models.CharField(help_text='Örn: Python, Django, Tailwind', max_length=200, verbose_name='Kullanılan Teknolojiler')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': 'Projeler',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
    ]
