# Generated by Django 5.1.4 on 2026-01-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calismalar', '0002_alter_proje_aciklama'),
    ]

    operations = [
        migrations.AddField(
            model_name='proje',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='proje',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
