# Generated by Django 5.1.4 on 2026-01-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yazilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Yazı Başlığı')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='URL Yolu')),
                ('resim', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Kapak Görseli')),
                ('icerik', models.TextField(verbose_name='Yazı İçeriği')),
                ('ozet', models.TextField(blank=True, help_text='Listede görünecek kısa açıklama', max_length=300)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('yayinda_mi', models.BooleanField(default=True, verbose_name='Yayında mı?')),
            ],
            options={
                'verbose_name': 'Blog Yazısı',
                'verbose_name_plural': 'Blog Yazıları',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
    ]
