# Generated by Django 5.1.4 on 2026-01-06 19:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazilar',
            name='icerik',
            field=ckeditor.fields.RichTextField(verbose_name='Yazı İçeriği'),
        ),
        migrations.AlterField(
            model_name='yazilar',
            name='ozet',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Listede görünecek kısa açıklama', max_length=300),
        ),
    ]
