# Generated by Django 6.0 on 2026-01-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='Gönderen Kişi')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta Adresi')),
                ('konu', models.CharField(max_length=200, verbose_name='Mesaj Konusu')),
                ('mesaj', models.TextField(verbose_name='Mesaj İçeriği')),
                ('okundu', models.BooleanField(default=False, verbose_name='Okundu mu?')),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='Gönderilme Tarihi')),
            ],
            options={
                'verbose_name': 'Gelen Mesaj',
                'verbose_name_plural': 'Gelen Mesajlar',
                'ordering': ['-tarih'],
            },
        ),
    ]
