# Generated by Django 5.1.4 on 2026-01-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iletisim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesaj',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
