# Generated by Django 6.0 on 2026-01-04 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL Yolu (Slug)')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='Egitim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Eğitim Başlığı')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL Yolu')),
                ('aciklama', models.TextField(blank=True, verbose_name='Kısa Açıklama')),
                ('resim', models.ImageField(blank=True, null=True, upload_to='egitim_resimleri/', verbose_name='Kapak Resmi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Yayında mı?')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egitimler', to='egitimler.kategori', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Eğitim',
                'verbose_name_plural': 'Eğitimler',
            },
        ),
    ]
