# Generated by Django 6.0 on 2026-01-04 21:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egitimler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egitim',
            name='aciklama',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Kısa Açıklama'),
        ),
    ]
