# Generated by Django 5.1.4 on 2026-01-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egitimler', '0002_alter_egitim_aciklama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egitim',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
